name: ⭐ Feature Request
description: Guided request for features
labels: ["enhancement"]
projects: ["VKx64/3"]
body:
  # Input element for describing the feature
  - type: textarea
    id: feature_description
    attributes:
      label: What is the feature?
      description: Provide a clear and detailed description of the feature you'd like to see.
      placeholder: "Example: A new dashboard for admins to manage users"
    validations:
      required: true

  # Date picker element for selecting the preferred completion date
  - type: input
    id: preferred_completion
    attributes:
      label: When is the preferred completion date?
      description: Select the desired date for when you would like this feature to be completed.
      placeholder: "YYYY-MM-DD"
    validations:
      required: true